/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SanityCheckRouteImport } from './routes/sanity-check'
import { Route as PingRouteImport } from './routes/ping'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewNikonLowResRouteImport } from './routes/review.nikon-low-res'
import { Route as ReviewDuplicatesRouteImport } from './routes/review.duplicates'
import { Route as ApiNikonLowResRouteImport } from './routes/api.nikon-low-res'
import { Route as ApiMarkForDeletionRouteImport } from './routes/api.mark-for-deletion'
import { Route as ReviewSimilarIndexRouteImport } from './routes/review.similar.index'
import { Route as ReviewCompareIndexRouteImport } from './routes/review.compare.index'
import { Route as ReviewSimilarIdRouteImport } from './routes/review.similar.$id'
import { Route as ApiThumbnailIdRouteImport } from './routes/api.thumbnail.$id'
import { Route as ApiSimilarIdRouteImport } from './routes/api.similar.$id'
import { Route as ApiComfyuiWorkflowsRouteImport } from './routes/api.comfyui.workflows'
import { Route as ApiComfyuiJobsRouteImport } from './routes/api.comfyui.jobs'
import { Route as ApiComfyuiGenerateRouteImport } from './routes/api.comfyui.generate'
import { Route as ReviewCompareId1Id2RouteImport } from './routes/review.compare.$id1.$id2'
import { Route as ApiTryIdId2RouteImport } from './routes/api.try.$id.$id2'
import { Route as ApiComfyuiJobsJobIdRouteImport } from './routes/api.comfyui.jobs.$jobId'

const SanityCheckRoute = SanityCheckRouteImport.update({
  id: '/sanity-check',
  path: '/sanity-check',
  getParentRoute: () => rootRouteImport,
} as any)
const PingRoute = PingRouteImport.update({
  id: '/ping',
  path: '/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewNikonLowResRoute = ReviewNikonLowResRouteImport.update({
  id: '/review/nikon-low-res',
  path: '/review/nikon-low-res',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewDuplicatesRoute = ReviewDuplicatesRouteImport.update({
  id: '/review/duplicates',
  path: '/review/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNikonLowResRoute = ApiNikonLowResRouteImport.update({
  id: '/api/nikon-low-res',
  path: '/api/nikon-low-res',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarkForDeletionRoute = ApiMarkForDeletionRouteImport.update({
  id: '/api/mark-for-deletion',
  path: '/api/mark-for-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewSimilarIndexRoute = ReviewSimilarIndexRouteImport.update({
  id: '/review/similar/',
  path: '/review/similar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewCompareIndexRoute = ReviewCompareIndexRouteImport.update({
  id: '/review/compare/',
  path: '/review/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewSimilarIdRoute = ReviewSimilarIdRouteImport.update({
  id: '/review/similar/$id',
  path: '/review/similar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThumbnailIdRoute = ApiThumbnailIdRouteImport.update({
  id: '/api/thumbnail/$id',
  path: '/api/thumbnail/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimilarIdRoute = ApiSimilarIdRouteImport.update({
  id: '/api/similar/$id',
  path: '/api/similar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComfyuiWorkflowsRoute = ApiComfyuiWorkflowsRouteImport.update({
  id: '/api/comfyui/workflows',
  path: '/api/comfyui/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComfyuiJobsRoute = ApiComfyuiJobsRouteImport.update({
  id: '/api/comfyui/jobs',
  path: '/api/comfyui/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComfyuiGenerateRoute = ApiComfyuiGenerateRouteImport.update({
  id: '/api/comfyui/generate',
  path: '/api/comfyui/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewCompareId1Id2Route = ReviewCompareId1Id2RouteImport.update({
  id: '/review/compare/$id1/$id2',
  path: '/review/compare/$id1/$id2',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTryIdId2Route = ApiTryIdId2RouteImport.update({
  id: '/api/try/$id/$id2',
  path: '/api/try/$id/$id2',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComfyuiJobsJobIdRoute = ApiComfyuiJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ApiComfyuiJobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/ping': typeof PingRoute
  '/sanity-check': typeof SanityCheckRoute
  '/api/mark-for-deletion': typeof ApiMarkForDeletionRoute
  '/api/nikon-low-res': typeof ApiNikonLowResRoute
  '/review/duplicates': typeof ReviewDuplicatesRoute
  '/review/nikon-low-res': typeof ReviewNikonLowResRoute
  '/api/comfyui/generate': typeof ApiComfyuiGenerateRoute
  '/api/comfyui/jobs': typeof ApiComfyuiJobsRouteWithChildren
  '/api/comfyui/workflows': typeof ApiComfyuiWorkflowsRoute
  '/api/similar/$id': typeof ApiSimilarIdRoute
  '/api/thumbnail/$id': typeof ApiThumbnailIdRoute
  '/review/similar/$id': typeof ReviewSimilarIdRoute
  '/review/compare/': typeof ReviewCompareIndexRoute
  '/review/similar/': typeof ReviewSimilarIndexRoute
  '/api/comfyui/jobs/$jobId': typeof ApiComfyuiJobsJobIdRoute
  '/api/try/$id/$id2': typeof ApiTryIdId2Route
  '/review/compare/$id1/$id2': typeof ReviewCompareId1Id2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/ping': typeof PingRoute
  '/sanity-check': typeof SanityCheckRoute
  '/api/mark-for-deletion': typeof ApiMarkForDeletionRoute
  '/api/nikon-low-res': typeof ApiNikonLowResRoute
  '/review/duplicates': typeof ReviewDuplicatesRoute
  '/review/nikon-low-res': typeof ReviewNikonLowResRoute
  '/api/comfyui/generate': typeof ApiComfyuiGenerateRoute
  '/api/comfyui/jobs': typeof ApiComfyuiJobsRouteWithChildren
  '/api/comfyui/workflows': typeof ApiComfyuiWorkflowsRoute
  '/api/similar/$id': typeof ApiSimilarIdRoute
  '/api/thumbnail/$id': typeof ApiThumbnailIdRoute
  '/review/similar/$id': typeof ReviewSimilarIdRoute
  '/review/compare': typeof ReviewCompareIndexRoute
  '/review/similar': typeof ReviewSimilarIndexRoute
  '/api/comfyui/jobs/$jobId': typeof ApiComfyuiJobsJobIdRoute
  '/api/try/$id/$id2': typeof ApiTryIdId2Route
  '/review/compare/$id1/$id2': typeof ReviewCompareId1Id2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/ping': typeof PingRoute
  '/sanity-check': typeof SanityCheckRoute
  '/api/mark-for-deletion': typeof ApiMarkForDeletionRoute
  '/api/nikon-low-res': typeof ApiNikonLowResRoute
  '/review/duplicates': typeof ReviewDuplicatesRoute
  '/review/nikon-low-res': typeof ReviewNikonLowResRoute
  '/api/comfyui/generate': typeof ApiComfyuiGenerateRoute
  '/api/comfyui/jobs': typeof ApiComfyuiJobsRouteWithChildren
  '/api/comfyui/workflows': typeof ApiComfyuiWorkflowsRoute
  '/api/similar/$id': typeof ApiSimilarIdRoute
  '/api/thumbnail/$id': typeof ApiThumbnailIdRoute
  '/review/similar/$id': typeof ReviewSimilarIdRoute
  '/review/compare/': typeof ReviewCompareIndexRoute
  '/review/similar/': typeof ReviewSimilarIndexRoute
  '/api/comfyui/jobs/$jobId': typeof ApiComfyuiJobsJobIdRoute
  '/api/try/$id/$id2': typeof ApiTryIdId2Route
  '/review/compare/$id1/$id2': typeof ReviewCompareId1Id2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/ping'
    | '/sanity-check'
    | '/api/mark-for-deletion'
    | '/api/nikon-low-res'
    | '/review/duplicates'
    | '/review/nikon-low-res'
    | '/api/comfyui/generate'
    | '/api/comfyui/jobs'
    | '/api/comfyui/workflows'
    | '/api/similar/$id'
    | '/api/thumbnail/$id'
    | '/review/similar/$id'
    | '/review/compare/'
    | '/review/similar/'
    | '/api/comfyui/jobs/$jobId'
    | '/api/try/$id/$id2'
    | '/review/compare/$id1/$id2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/ping'
    | '/sanity-check'
    | '/api/mark-for-deletion'
    | '/api/nikon-low-res'
    | '/review/duplicates'
    | '/review/nikon-low-res'
    | '/api/comfyui/generate'
    | '/api/comfyui/jobs'
    | '/api/comfyui/workflows'
    | '/api/similar/$id'
    | '/api/thumbnail/$id'
    | '/review/similar/$id'
    | '/review/compare'
    | '/review/similar'
    | '/api/comfyui/jobs/$jobId'
    | '/api/try/$id/$id2'
    | '/review/compare/$id1/$id2'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/ping'
    | '/sanity-check'
    | '/api/mark-for-deletion'
    | '/api/nikon-low-res'
    | '/review/duplicates'
    | '/review/nikon-low-res'
    | '/api/comfyui/generate'
    | '/api/comfyui/jobs'
    | '/api/comfyui/workflows'
    | '/api/similar/$id'
    | '/api/thumbnail/$id'
    | '/review/similar/$id'
    | '/review/compare/'
    | '/review/similar/'
    | '/api/comfyui/jobs/$jobId'
    | '/api/try/$id/$id2'
    | '/review/compare/$id1/$id2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  PingRoute: typeof PingRoute
  SanityCheckRoute: typeof SanityCheckRoute
  ApiMarkForDeletionRoute: typeof ApiMarkForDeletionRoute
  ApiNikonLowResRoute: typeof ApiNikonLowResRoute
  ReviewDuplicatesRoute: typeof ReviewDuplicatesRoute
  ReviewNikonLowResRoute: typeof ReviewNikonLowResRoute
  ApiComfyuiGenerateRoute: typeof ApiComfyuiGenerateRoute
  ApiComfyuiJobsRoute: typeof ApiComfyuiJobsRouteWithChildren
  ApiComfyuiWorkflowsRoute: typeof ApiComfyuiWorkflowsRoute
  ApiSimilarIdRoute: typeof ApiSimilarIdRoute
  ApiThumbnailIdRoute: typeof ApiThumbnailIdRoute
  ReviewSimilarIdRoute: typeof ReviewSimilarIdRoute
  ReviewCompareIndexRoute: typeof ReviewCompareIndexRoute
  ReviewSimilarIndexRoute: typeof ReviewSimilarIndexRoute
  ApiTryIdId2Route: typeof ApiTryIdId2Route
  ReviewCompareId1Id2Route: typeof ReviewCompareId1Id2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sanity-check': {
      id: '/sanity-check'
      path: '/sanity-check'
      fullPath: '/sanity-check'
      preLoaderRoute: typeof SanityCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ping': {
      id: '/ping'
      path: '/ping'
      fullPath: '/ping'
      preLoaderRoute: typeof PingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/nikon-low-res': {
      id: '/review/nikon-low-res'
      path: '/review/nikon-low-res'
      fullPath: '/review/nikon-low-res'
      preLoaderRoute: typeof ReviewNikonLowResRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/duplicates': {
      id: '/review/duplicates'
      path: '/review/duplicates'
      fullPath: '/review/duplicates'
      preLoaderRoute: typeof ReviewDuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nikon-low-res': {
      id: '/api/nikon-low-res'
      path: '/api/nikon-low-res'
      fullPath: '/api/nikon-low-res'
      preLoaderRoute: typeof ApiNikonLowResRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mark-for-deletion': {
      id: '/api/mark-for-deletion'
      path: '/api/mark-for-deletion'
      fullPath: '/api/mark-for-deletion'
      preLoaderRoute: typeof ApiMarkForDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/similar/': {
      id: '/review/similar/'
      path: '/review/similar'
      fullPath: '/review/similar/'
      preLoaderRoute: typeof ReviewSimilarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/compare/': {
      id: '/review/compare/'
      path: '/review/compare'
      fullPath: '/review/compare/'
      preLoaderRoute: typeof ReviewCompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/similar/$id': {
      id: '/review/similar/$id'
      path: '/review/similar/$id'
      fullPath: '/review/similar/$id'
      preLoaderRoute: typeof ReviewSimilarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/thumbnail/$id': {
      id: '/api/thumbnail/$id'
      path: '/api/thumbnail/$id'
      fullPath: '/api/thumbnail/$id'
      preLoaderRoute: typeof ApiThumbnailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/similar/$id': {
      id: '/api/similar/$id'
      path: '/api/similar/$id'
      fullPath: '/api/similar/$id'
      preLoaderRoute: typeof ApiSimilarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comfyui/workflows': {
      id: '/api/comfyui/workflows'
      path: '/api/comfyui/workflows'
      fullPath: '/api/comfyui/workflows'
      preLoaderRoute: typeof ApiComfyuiWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comfyui/jobs': {
      id: '/api/comfyui/jobs'
      path: '/api/comfyui/jobs'
      fullPath: '/api/comfyui/jobs'
      preLoaderRoute: typeof ApiComfyuiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comfyui/generate': {
      id: '/api/comfyui/generate'
      path: '/api/comfyui/generate'
      fullPath: '/api/comfyui/generate'
      preLoaderRoute: typeof ApiComfyuiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/compare/$id1/$id2': {
      id: '/review/compare/$id1/$id2'
      path: '/review/compare/$id1/$id2'
      fullPath: '/review/compare/$id1/$id2'
      preLoaderRoute: typeof ReviewCompareId1Id2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/try/$id/$id2': {
      id: '/api/try/$id/$id2'
      path: '/api/try/$id/$id2'
      fullPath: '/api/try/$id/$id2'
      preLoaderRoute: typeof ApiTryIdId2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comfyui/jobs/$jobId': {
      id: '/api/comfyui/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/api/comfyui/jobs/$jobId'
      preLoaderRoute: typeof ApiComfyuiJobsJobIdRouteImport
      parentRoute: typeof ApiComfyuiJobsRoute
    }
  }
}

interface ApiComfyuiJobsRouteChildren {
  ApiComfyuiJobsJobIdRoute: typeof ApiComfyuiJobsJobIdRoute
}

const ApiComfyuiJobsRouteChildren: ApiComfyuiJobsRouteChildren = {
  ApiComfyuiJobsJobIdRoute: ApiComfyuiJobsJobIdRoute,
}

const ApiComfyuiJobsRouteWithChildren = ApiComfyuiJobsRoute._addFileChildren(
  ApiComfyuiJobsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  PingRoute: PingRoute,
  SanityCheckRoute: SanityCheckRoute,
  ApiMarkForDeletionRoute: ApiMarkForDeletionRoute,
  ApiNikonLowResRoute: ApiNikonLowResRoute,
  ReviewDuplicatesRoute: ReviewDuplicatesRoute,
  ReviewNikonLowResRoute: ReviewNikonLowResRoute,
  ApiComfyuiGenerateRoute: ApiComfyuiGenerateRoute,
  ApiComfyuiJobsRoute: ApiComfyuiJobsRouteWithChildren,
  ApiComfyuiWorkflowsRoute: ApiComfyuiWorkflowsRoute,
  ApiSimilarIdRoute: ApiSimilarIdRoute,
  ApiThumbnailIdRoute: ApiThumbnailIdRoute,
  ReviewSimilarIdRoute: ReviewSimilarIdRoute,
  ReviewCompareIndexRoute: ReviewCompareIndexRoute,
  ReviewSimilarIndexRoute: ReviewSimilarIndexRoute,
  ApiTryIdId2Route: ApiTryIdId2Route,
  ReviewCompareId1Id2Route: ReviewCompareId1Id2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
