/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import {Route as rootRouteImport} from './routes/__root'
import {Route as PingRouteImport} from './routes/ping'
import {Route as DuplicatesRouteImport} from './routes/duplicates'
import {Route as AssetsRouteImport} from './routes/assets'
import {Route as IndexRouteImport} from './routes/index'
import {Route as ReviewNikonLowResRouteImport} from './routes/review.nikon-low-res'
import {Route as ApiNikonLowResRouteImport} from './routes/api.nikon-low-res'
import {Route as ApiMarkForDeletionRouteImport} from './routes/api.mark-for-deletion'
import {Route as ReviewDuplicatesAssetIdRouteImport} from './routes/review.duplicates.$assetId'
import {Route as ApiThumbnailIdRouteImport} from './routes/api.thumbnail.$id'
import {Route as ApiSimilarIdRouteImport} from './routes/api.similar.$id'
import {Route as ApiTryIdId2RouteImport} from './routes/api.try.$id.$id2'

const PingRoute = PingRouteImport.update({
  id: '/ping',
  path: '/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicatesRoute = DuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewNikonLowResRoute = ReviewNikonLowResRouteImport.update({
  id: '/review/nikon-low-res',
  path: '/review/nikon-low-res',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNikonLowResRoute = ApiNikonLowResRouteImport.update({
  id: '/api/nikon-low-res',
  path: '/api/nikon-low-res',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarkForDeletionRoute = ApiMarkForDeletionRouteImport.update({
  id: '/api/mark-for-deletion',
  path: '/api/mark-for-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewDuplicatesAssetIdRoute = ReviewDuplicatesAssetIdRouteImport.update({
  id: '/review/duplicates/$assetId',
  path: '/review/duplicates/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThumbnailIdRoute = ApiThumbnailIdRouteImport.update({
  id: '/api/thumbnail/$id',
  path: '/api/thumbnail/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimilarIdRoute = ApiSimilarIdRouteImport.update({
  id: '/api/similar/$id',
  path: '/api/similar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTryIdId2Route = ApiTryIdId2RouteImport.update({
  id: '/api/try/$id/$id2',
  path: '/api/try/$id/$id2',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/duplicates': typeof DuplicatesRoute
  '/ping': typeof PingRoute
  '/api/mark-for-deletion': typeof ApiMarkForDeletionRoute
  '/api/nikon-low-res': typeof ApiNikonLowResRoute
  '/review/nikon-low-res': typeof ReviewNikonLowResRoute
  '/api/similar/$id': typeof ApiSimilarIdRoute
  '/api/thumbnail/$id': typeof ApiThumbnailIdRoute
  '/review/duplicates/$assetId': typeof ReviewDuplicatesAssetIdRoute
  '/api/try/$id/$id2': typeof ApiTryIdId2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/duplicates': typeof DuplicatesRoute
  '/ping': typeof PingRoute
  '/api/mark-for-deletion': typeof ApiMarkForDeletionRoute
  '/api/nikon-low-res': typeof ApiNikonLowResRoute
  '/review/nikon-low-res': typeof ReviewNikonLowResRoute
  '/api/similar/$id': typeof ApiSimilarIdRoute
  '/api/thumbnail/$id': typeof ApiThumbnailIdRoute
  '/review/duplicates/$assetId': typeof ReviewDuplicatesAssetIdRoute
  '/api/try/$id/$id2': typeof ApiTryIdId2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/duplicates': typeof DuplicatesRoute
  '/ping': typeof PingRoute
  '/api/mark-for-deletion': typeof ApiMarkForDeletionRoute
  '/api/nikon-low-res': typeof ApiNikonLowResRoute
  '/review/nikon-low-res': typeof ReviewNikonLowResRoute
  '/api/similar/$id': typeof ApiSimilarIdRoute
  '/api/thumbnail/$id': typeof ApiThumbnailIdRoute
  '/review/duplicates/$assetId': typeof ReviewDuplicatesAssetIdRoute
  '/api/try/$id/$id2': typeof ApiTryIdId2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/duplicates'
    | '/ping'
    | '/api/mark-for-deletion'
    | '/api/nikon-low-res'
    | '/review/nikon-low-res'
    | '/api/similar/$id'
    | '/api/thumbnail/$id'
    | '/review/duplicates/$assetId'
    | '/api/try/$id/$id2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/duplicates'
    | '/ping'
    | '/api/mark-for-deletion'
    | '/api/nikon-low-res'
    | '/review/nikon-low-res'
    | '/api/similar/$id'
    | '/api/thumbnail/$id'
    | '/review/duplicates/$assetId'
    | '/api/try/$id/$id2'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/duplicates'
    | '/ping'
    | '/api/mark-for-deletion'
    | '/api/nikon-low-res'
    | '/review/nikon-low-res'
    | '/api/similar/$id'
    | '/api/thumbnail/$id'
    | '/review/duplicates/$assetId'
    | '/api/try/$id/$id2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  DuplicatesRoute: typeof DuplicatesRoute
  PingRoute: typeof PingRoute
  ApiMarkForDeletionRoute: typeof ApiMarkForDeletionRoute
  ApiNikonLowResRoute: typeof ApiNikonLowResRoute
  ReviewNikonLowResRoute: typeof ReviewNikonLowResRoute
  ApiSimilarIdRoute: typeof ApiSimilarIdRoute
  ApiThumbnailIdRoute: typeof ApiThumbnailIdRoute
  ReviewDuplicatesAssetIdRoute: typeof ReviewDuplicatesAssetIdRoute
  ApiTryIdId2Route: typeof ApiTryIdId2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ping': {
      id: '/ping'
      path: '/ping'
      fullPath: '/ping'
      preLoaderRoute: typeof PingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplicates': {
      id: '/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof DuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/nikon-low-res': {
      id: '/review/nikon-low-res'
      path: '/review/nikon-low-res'
      fullPath: '/review/nikon-low-res'
      preLoaderRoute: typeof ReviewNikonLowResRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nikon-low-res': {
      id: '/api/nikon-low-res'
      path: '/api/nikon-low-res'
      fullPath: '/api/nikon-low-res'
      preLoaderRoute: typeof ApiNikonLowResRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mark-for-deletion': {
      id: '/api/mark-for-deletion'
      path: '/api/mark-for-deletion'
      fullPath: '/api/mark-for-deletion'
      preLoaderRoute: typeof ApiMarkForDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/duplicates/$assetId': {
      id: '/review/duplicates/$assetId'
      path: '/review/duplicates/$assetId'
      fullPath: '/review/duplicates/$assetId'
      preLoaderRoute: typeof ReviewDuplicatesAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/thumbnail/$id': {
      id: '/api/thumbnail/$id'
      path: '/api/thumbnail/$id'
      fullPath: '/api/thumbnail/$id'
      preLoaderRoute: typeof ApiThumbnailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/similar/$id': {
      id: '/api/similar/$id'
      path: '/api/similar/$id'
      fullPath: '/api/similar/$id'
      preLoaderRoute: typeof ApiSimilarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/try/$id/$id2': {
      id: '/api/try/$id/$id2'
      path: '/api/try/$id/$id2'
      fullPath: '/api/try/$id/$id2'
      preLoaderRoute: typeof ApiTryIdId2RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  DuplicatesRoute: DuplicatesRoute,
  PingRoute: PingRoute,
  ApiMarkForDeletionRoute: ApiMarkForDeletionRoute,
  ApiNikonLowResRoute: ApiNikonLowResRoute,
  ReviewNikonLowResRoute: ReviewNikonLowResRoute,
  ApiSimilarIdRoute: ApiSimilarIdRoute,
  ApiThumbnailIdRoute: ApiThumbnailIdRoute,
  ReviewDuplicatesAssetIdRoute: ReviewDuplicatesAssetIdRoute,
  ApiTryIdId2Route: ApiTryIdId2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type {getRouter} from './router.tsx'
import type {createStart} from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
